### ISSUE TITLE
New smelting system bug

### ISSUE THREAD

**Issue by Cynix32** [AlgorithmLX-Team/DimOre#5]
Title says it all, here is the console log:https://pastebin.com/hL3456qL
Forge 36.2.20
MC 1.16.5
crossroads-1.16.5-2.6.5.jar
Dimensional_Ores-1.16.5-1.0.0.8.jar
essentials-1.16.5-2.11.1.jar (dependency of crossroads
Patchouli-1.16.4-53.2.jar (dependency of crossroads)

**Comment by AlgorithmLX** [comment]
try to install version 1.0.0.7, and disable updates (done in the config), and already in 1.0.0.9 I'll try to fix it (although according to the logs, the problem is Crossroads( Missing required tags: minecraft:block:crossroads:alchemy_rock )

**Comment by Cynix32** [comment]
It is still not fixed, datapack load error still occurs on existing worlds. Haven't tested it in new worlds tho. I tried a clean install with only these files (all downloaded from curseforge):

crossroads-1.16.5-2.6.5.jar
Dimensional_Ores-1.16.5-1.0.0.9.jar
essentials-1.16.5-2.11.1.jar
Patchouli-1.16.4-53.2.jar

**Comment by AlgorithmLX** [comment]
well then the problem is not in my mod

**Comment by AlgorithmLX** [comment]
and i was talking about this theme
![image](https://user-images.githubusercontent.com/46783751/147830394-413ef5d7-8327-4e92-8f1c-b929f35bf863.png)

**Comment by Cynix32** [comment]
And now again I am back to report that using Dimensional_Ores-1.16.5-1.0.0.7.jar does not fix the problem.
