### ISSUE TITLE
Config not checked for mod integration

### ISSUE THREAD

**Issue by Da-Technomancer** [AlgorithmLX-Team/DimOre#6]
The config option is not used for checking whether to perform mod integration when generating copper and tin ore, except for "thermal_foundation". The config is ignored for "mekanism" and "immersiveengineering". 
The issue is due to missing parenthesis; it's an order-of-operations issue for boolean operations. 

https://github.com/AlgorithmLX-Team/DimOre/blob/69d10433dd02bea3898971e8649eb3e4a9473955/src/main/java/com/algorithmlx/dimore/setup/DimOreReg.java#L76-L84

**Comment by Da-Technomancer** [comment]
Also, as a feature suggestion: a config to force the nether/end copper/tin ore to spawn, regardless of installed mods, would probably be a good idea, in case someone is using a mod with copper/tin other than mekanism, immersive engineering, or thermal foundation.

**Comment by AlgorithmLX** [comment]
hmm.. then I will only leave the config to check so that the ore does not depend on these mods. I was just going to make sure that ore appears only when these mods are installed, but apparently I have to abandon this idea

**Comment by AlgorithmLX** [comment]
fixed, thanks for reporting
